[package]
name = "prodev"
version = "0.1.0"
authors = ["Ethan D. Frei <ethan.frei@gmail.com>"]

[dependencies]
nickel = "0.9"
nickel_sqlite = "0.3"
rustc-serialize = "0.3"
cookie = "0.7"
hyper = "0.9"
rusqlite = { version = "0.9", features = ["bundled"] }
r2d2 = "0.7"
r2d2_sqlite = "0.1"
