[package]
name = "prodev"
version = "0.1.0"
authors = ["Ethan D. Frei <ethan.frei@gmail.com>"]

[dependencies]
nickel = "0.9.0"
# nickel_mustache = "0.1.0"
rustc-serialize = "0.3.21"
cookie = "0.2.5"
hyper = "0.9.12"
