[package]
name = "prodev"
version = "0.1.0"
authors = ["Ethan D. Frei <ethan.frei@gmail.com>"]

[dependencies]
nickel = "0.9.0"
nickel_sqlite = "0.3.0"
rustc-serialize = "0.3.21"
cookie = "0.2.5"
hyper = "0.9.12"
rusqlite = "0.7.3"
r2d2 = "0.7.1"
r2d2_sqlite = "0.1.0"
